# Generated by Django 3.2.6 on 2021-08-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210830_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
