# Generated by Django 3.2.6 on 2021-09-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='auth.user'),
            preserve_default=False,
        ),
    ]
