# Generated by Django 3.2.6 on 2021-09-06 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_requisition_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
