# Generated by Django 3.2.6 on 2021-09-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210906_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
